services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
    ports:
      - "8000:8000"


# To create from scratch
# docker-compose up --build

# To stop all and destroy
# docker-compose down -v

