# Generated by Django 3.1.4 on 2020-12-19 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('sno', models.AutoField(db_column='sno', primary_key=True, serialize=False)),
                ('timestamp', models.BigIntegerField(db_column='timestamp', default=exp.models.timestamp)),
                ('exp_type', models.CharField(db_column='exp_type', max_length=25)),
                ('sub_type', models.CharField(db_column='sub_type', max_length=25)),
                ('amount', models.IntegerField(db_column='amount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=exp.models.name_image, max_length=20)),
                ('img', models.ImageField(upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('sno', models.AutoField(db_column='sno', primary_key=True, serialize=False)),
                ('timestamp', models.BigIntegerField(db_column='timestamp', default=exp.models.timestamp)),
                ('exp_type', models.CharField(db_column='exp_type', max_length=25)),
                ('sub_type', models.CharField(db_column='sub_type', max_length=25)),
                ('amount', models.IntegerField(db_column='amount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
